#!/usr/bin/env sh

#terminate already running bar instances
killall -q polybar

#wait until the processes have been shutdown
while pgrep -x polybar >/dev/null; do sleep 1; done

#launch
polybar example &

echo "Bar launched..."
